image: ruby:2.1

before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh

stages:
  - test

variables:
  -TRAVIS_CI_TEST=true
  
job1:
  stage: test
  script:
    - asdf plugin-test julia https://github.com/rkyleg/asdf-julia.git 'julia --version'
  only:
    - master