language: c
script: asdf plugin-test julia $TRAVIS_BUILD_DIR 'julia --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
env:
  - CI_SERVER=yes
os:
  - linux
  - osx
